FROM node:20

# Install Python
RUN apt-get update && apt-get install -y python3 python3-pip

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

# Expose port
EXPOSE 3000

# Start app
CMD ["npm", "run", "prod"]
